import LoadableComponent from './../Loadable/index';
import {
  HomeOutlined,
  UserOutlined,
  TagsOutlined,
  AppstoreOutlined,
  DatabaseOutlined,
  ContainerOutlined,
  UserAddOutlined,
} from '@ant-design/icons';

export const userRouter: any = [
  {
    path: '/user',
    name: 'user',
    title: 'User',
    component: LoadableComponent(() => import('../../components/Layout/UserLayout')),
    isLayout: true,
    showInMenu: false,
  },
  {
    path: '/user/login',
    name: 'login',
    title: 'LogIn',
    component: LoadableComponent(() => import('../../scenes/Login')),
    showInMenu: false,
  },
];

export const appRouters: any = [
  {
    path: '/',
    exact: true,
    name: 'home',
    permission: '',
    title: 'Home',
    component: LoadableComponent(() => import('../../components/Layout/AppLayout')),
    isLayout: true,
    showInMenu: false,
  },
  {
    path: '/dashboard',
    name: 'dashboard',
    permission: '',
    title: 'Dashboard',
    icon: HomeOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Dashboard')),
  },
  {
    path: '/users',
    permission: 'Pages.Users',
    title: 'Users',
    name: 'user',
    icon: UserOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Users')),
  },
  {
    path: '/roles',
    permission: 'Pages.Roles',
    title: 'Roles',
    name: 'role',
    icon: TagsOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Roles')),
  },
  {
    path: '/tenants',
    permission: 'Pages.Tenants',
    title: 'Tenants',
    name: 'tenant',
    icon: AppstoreOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Tenants')),
  },
  {
    path: '/products',
    permission: '',
    title: 'Products',
    name: 'product',
    icon: DatabaseOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Products')),
  },
  {
    path: '/corporatedebits',
    permission: '',
    title: 'Corporate Debits',
    name: 'corporatedebit',
    icon: ContainerOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/CorporateDebits')),
  },
  {
    path: '/personeldebits',
    permission: '',
    title: 'Personel Debits',
    name: 'personeldebit',
    icon: UserAddOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/PersonelDebits')),
  },
  {
    path: '/logout',
    permission: '',
    title: 'Logout',
    name: 'logout',
    showInMenu: false,
    component: LoadableComponent(() => import('../../components/Logout')),
  },
  {
    path: '/exception?:type',
    permission: '',
    title: 'exception',
    name: 'exception',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Exception')),
  },
];

export const routers = [...userRouter, ...appRouters];
